const constants = {
	CHANGE_SEARCH_VARIABLE: 'CHANGE_SEARCH_VARIABLE',
	CLEAR_SEARCH_VARIABLE: 'CLEAR_SEARCH_VARIABLE',
	CHANGE_FILTER_BODY: 'CHANGE_FILTER_BODY',
	CLEAR_FILTER_BODY: 'CLEAR_FILTER_BODY',
	SET_CURRENT_CERTIFICATES: 'FETCH_CERTIFICATES',
	CHANGE_PAGE_NUMBER: 'CHANGE_PAGE_NUMBER',
	CHANGE_PER_PAGE_NUMBER: 'CHANGE_PER_PAGE_NUMBER',
	CHANGE_QUANTITY_OF_PAGES: 'CHANGE_QUANTITY_OF_PAGES',

	ADD_ERROR: 'ADD_ERROR',
	ADD_SUCCESS_MESSAGE: 'ADD_SUCCESS_MESSAGE',
	CLEAR_ERROR: 'CLEAR_ERROR',
	CLEAR_SUCCESS_MESSAGE: 'CLEAR_SUCCESS_MESSAGE',

	SET_USER_CERTIFICATES: 'SET_USER_CERTIFICATES',
	SHOW_USER_CERTIFICATES: 'SHOW_USER_CERTIFICATES',

	SET_USER: 'SET_USER',
	CLEAR_USER: 'CLEAR_USER',
	FETCH_USER: 'FETCH_USER',
};

export default constants